# Generated by Django 6.0.2 on 2026-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('Specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
