# Generated by Django 6.0.2 on 2026-02-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('Department', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
        ),
    ]
